version: '2.2'

services:
  pihole:
    container_name: pihole-reddit
    image: pihole/pihole:latest
    hostname: pihole
  #  domainname: example.com             # <-- Update
    mac_address: d0:ca:ab:cd:ef:01
    cap_add:
      - NET_ADMIN
    networks:
      pistatic-network:
        ipv4_address: 172.22.0.10    # NEW INTERFACE for trafic with synology
      pihole_network:
        ipv4_address: 192.168.1.199   # <-- Update
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 9.9.9.9
      - 1.1.1.1
    ports:
      - 443/tcp
      - 53/tcp
      - 53/udp
      - 67/udp
      - 80/tcp
    environment:
      ServerIP: 192.168.1.199        # <-- Update (match ipv4_address)
   #   VIRTUAL_HOST: pihole.example.com  # <-- Update (match hostname + domainname)
      WEBPASSWORD: "abcdefgh"                   # <-- Add password (if required)
    restart: unless-stopped
networks:
  pistatic-network:
    ipam:
      config:
        - subnet: 172.22.0.10/24
  pihole_network:
    driver: macvlan
    driver_opts:
      parent: ovs_eth0
    ipam:
      config:
        - subnet: 192.168.1.0/24            # <-- Update
          gateway: 192.168.1.1              # <-- Update
          ip_range: 192.168.1.192/28        # <-- Update
